blog_project/mysite/blog/urls.py
from blog import views
from django.conf.urls import url,include

app_name = 'blog'

urlpatterns = [
    url(r'^$',views.PostListView.as_view(), name='post_list'),
    url(r'^about/$',views.AboutView.as_view(),name='about'),
    url(r'^post/(?P<pk>\d+)$',views.PostDetailView.as_view(),name='post_detail'),
    url(r'^post/new/$',views.CreatePostView.as_view(),name='post_new'),
    url(r'^post/(?P<pk>\d+)/edit/$',views.UpdatePostView.as_view(),name='post_edit'),
    url(r'^post/(?P<pk>\d+)/remove/$',views.DeletePostView.as_view(),name='post_remove'),
    url(r'^drafts/$',views.DraftListView.as_view(),name='post_draft_list'),
    url(r'^post/(?P<pk>\d+)/comment/$',views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^post/(?P<pk>\d+)/publish/$',views.post_publish, name='post_publish'),
    url(r'^comment/(?P<pk>\d+)/remove/$',views.comment_remove,name='comment_remove'),
    url(r'^comment/(?P<pk>\d+)/approve/$',views.comment_approve, name='comment_approve'),
]

blog_project/mysite/mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('blog.urls')),
    url(r'^accounts/login/$',views.login,name='login'),
    url(r'^accounts/logout/$',views.logout, name='logout',kwargs={'next_page':'/'}),

]

blog_project/mysite/blog/models.py
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse

# Create your models here.

class Post(models.Model):
    author = models.CharField(max_length = 264)
    text = models.TextField()
    title = models.CharField(max_length = 264)
    create_date = models.DateTimeField(default = timezone.now)
    published_date = models.DateTimeField(blank = True, null = True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()
    def approve_comments(self):
        return self.comment.filter(approved_comment  = True)
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'pk':self.pk})

class Comment(models.Model):
    post = models.ForeignKey(Post,related_name = 'comment')
    author = models.CharField(max_length = 264)
    text = models.TextField()
    create_date = models.DateTimeField(default = timezone.now)
    approved_comment = models.BooleanField(default = False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def get_absolute_url(self):
        return reverse('blog:post_list')

    def __str__(self):
        return self.text

blog_project/mysite/blog/forms.py
from django import forms
from blog.models import Post,Comment

class PostForm(forms.ModelForm):
    class Meta():
        model = Post
        fields = ('author','text','title')
        widgets = {
            'title':forms.TextInput(attrs={'class':'textinputclass'}),
            'text':forms.Textarea(attrs={'class':'editable medium-editor-textarea postcontent'})
        }

class CommentForm(forms.ModelForm):
    class Meta():
        model = Comment
        fields = ('author','text')
        widgets = {
            'author':forms.TextInput(attrs={'class':'textinputclass'}),
            'text':forms.Textarea(attrs={'class':'editable medium-editor-textarea'})
        }

blog_project/mysite/blog/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.utils import timezone
from blog import models
from blog import forms
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView,CreateView,UpdateView,DeleteView,ListView,DetailView
from django.urls import reverse_lazy
# Create your views here.

class AboutView(TemplateView):
    template_name = 'about.html'

class PostListView(ListView):
    model = models.Post
    def get_queryset(self):
        return models.Post.objects.filter(published_date__lte = timezone.now()).order_by('-published_date')

class PostDetailView(DetailView):
    model = models.Post
    #template_name = 'post_detail.html'

class CreatePostView(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    #redirect_field_name = 'blog/post_detail.html'
    form_class = forms.PostForm
    model = models.Post
    

class UpdatePostView(LoginRequiredMixin,UpdateView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_list.html'
    model = models.Post
    form_class = forms.PostForm

class DeletePostView(DeleteView):
    model = models.Post
    success_url = reverse_lazy('blog:post_list')

class DraftListView(LoginRequiredMixin,ListView):
    url = '/login/'
    redirect_field_name = 'blog:post_list'
    model = models.Post
    template_name = 'post_draft_list.html'

    def get_queryset(self):
        return models.Post.objects.filter(published_date__isnull = True).order_by('-create_date')

@login_required
def post_publish(request,pk):
    post = get_object_or_404(models.Post,pk =pk)
    post.publish()
    return redirect('blog:post_detail',pk = post.pk)

@login_required
def add_comment_to_post(request,pk):
    post = get_object_or_404(models.Post, pk=pk)
    if request.method == 'POST':
        form = forms.CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit = False)
            comment.post = post
            comment.save()
            return redirect('blog:post_detail',pk=post.pk)
    else:
        form = forms.CommentForm()
    return render(request,'blog/comment_form.html',{'form':form}) #this seems wrong

@login_required
def comment_approve(request,pk):
    comment = get_object_or_404(models.Comment, pk=pk)
    comment.approve()
    return redirect('blog:post_detail',pk = comment.post.pk)


@login_required
def comment_remove(request,pk):
    comment = get_object_or_404(models.Comment,pk = pk)
    saving_for_future_coz_later_will_be_deleted = comment.post.pk
    comment.delete()
    return redirect('blog:post_detail',pk = saving_for_future_coz_later_will_be_deleted)        

blog_project/mysite/blog/templates/blog/about.html
{%extends 'blog/base.html'%}

{%block title_block%}
    ABOUT PAGE
{%endblock%}

{%block body_block%}
    <h1>HELLO AND WELCOME TO MY SITE</h1>
    <h2>Enjoy the blogs</h2>
{%endblock%}

blog_project/mysite/blog/templates/blog/base.html
<!DOCTYPE html>
<html>
    <meta charset="utf-8">
    
    
    <link href="https://fonts.googleapis.com/css2?family=Red+Rose&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Teko:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap" rel="stylesheet">




    
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    
        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
            integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">


    
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css"
        media="screen" charset="utf-8">


    <head>
        
        <title>{%block title_block%}

            {%endblock%}
        </title>
    </head>
    <body>
        <nav class="navbar navbar-inverse technofont">
            <div class="container">
                <ul class="nav navbar-nav">
                    <li><a class="navbar-brand bigbrand " href="{%url 'blog:post_list'%}">BLOGS</a></li>
                    <li><a class="navbar-link " href="{% url 'blog:about'%}">ABOUT</a></li>
                    <li><a class="navbar-link " href="https://github.com/vinaydahiya04/">GITHUB</a></li>
                    <li><a class="navbar-link " href="https://in.linkedin.com/in/vinay-dahiya-3438931b1">LINKEDIN</a></li>
                </ul>
                <div class="pull-right">
                    <ul class="nav navbar-nav">
                        {% if user.is_authenticated%}
                        <li>
                            <a href="{% url 'blog:post_new'%}">NEW BLOG</a>
                        </li>
                        <li>
                            <a href="{% url 'blog:post_draft_list'%}">DRAFTS</a>
                        </li>
                        <li>
                            <a href="{% url 'logout'%}">LOGOUT</a>
                        </li>
                        <li>
                            <a>WELCOME : {{user.username}} </a>
                        </li>
                        {%else%}
                        <li>
                            <a href="{% url 'login' %}"><span class="glyphicon glyphicon-user"></span></a>
                        </li>
                    
                        {%endif%}
                    
                    </ul>
                </div>

            </div>
            
        </nav>

        <br>
        <br>
        <div class="container jumbotron content">
            {%block body_block%}
            {%endblock%}
        </div>
    </body>

</html>

blog_project/mysite/blog/templates/blog/blog.html
{%extends 'blog/base.html'%}

{%block title_block%}
BLOG HTML
{%endblock%}

{%block body_block%}
{%endblock%}

blog_project/mysite/blog/templates/blog/comment_form.html
{%extends 'blog/base.html'%}

{%block title_block%}
COMMENT FORM
{%endblock%}

{%block body_block%}
    <form class="post_form" method="POST">
        {%csrf_token%}
        {{form.as_p}}
        <button type="submit" class="btn btn-default">POST COMMENT</button>
    </form>
    <script>var editor = new MediumEditor('.editable');</script>
{%endblock%}

blog_project/mysite/blog/templates/blog/post_confirm_delete.html
{%extends 'blog/base.html'%}

{%block title_block%}
CONFIRM DELETE
{%endblock%}

{%block body_block%}
<h1>ARE YOU SURE YOU WANT TO DELETE {{ object }} POST</h1>
<form method="POST">
    {%csrf_token%}
    <input type="submit" class="btn btn-danger" value="Delete Comment">
</form>
{%endblock%}

blog_project/mysite/blog/templates/blog/post_detail.html
{%extends 'blog/base.html'%}

{%block title_block%}
POST DETAIL
{%endblock%}

{%block body_block%}
<h1 class="post title">{{post.title}}</h1>
{%if post.published_date%}
<div class="date">
    {{post.published_date}}
</div>
{%else%}

<a class="btn btn-primary" href="{%url 'blog:post_publish' pk=post.pk%}">PUBLISH</a>
{%endif%}

<p class="postcontent">{{post.text|safe|linebreaksbr}}</p>

{%if user.is_authenticated%}
<a class="btn btn-primary" href="{% url 'blog:post_edit' pk=post.pk%}"><span class="glyphicon glyphicon-pencil"></span></a>
<a class="btn btn-primary" href="{% url 'blog:post_remove' pk=post.pk%}"><span class="glyphicon glyphicon-remove"></span></a>
<hr>
{%endif%}
<a class="btn btn-primary" href="{% url 'blog:add_comment_to_post' pk=post.pk %}">ADD COMMENT</a>



{% for comment in post.comment.all%}
{%if user.is_authenticated or comment.approved_comment %}
    {{comment.created_date}}
    {%if not comment.comment_approved%}
        <a class="btn btn-primary" href="{%url 'blog:comment_approve' pk=comment.pk%}"><span class="glyphicon glyphicon-ok"></span></a>
        <a class="btn btn-primary" href="{%url 'blog:comment_remove' pk=comment.pk%}"><span class="glyphicon glyphicon-remove"></span></a>

{%endif%}
    <p>{{comment.text|safe|linebreaksbr}}</p>
    <p>{{comment.author}}</p>
{%endif%}
{%empty%}
<p>NO COMMENTS</p>
{%endfor%}
{%endblock%}

blog_project/mysite/blog/templates/blog/post_draft_list.html
{%extends 'base.html'%}

{%block title_block%}
POST DRAFT LIST
{%endblock%}

{%block body_block%}
{%for post in post_list%}
    <div class="post">
        <h3>Date Created : {{post.create_date|date:"d M Y"}}</h3>
        <h1><a href="{%url 'blog:post_detail' pk=post.pk%}">{{post.title}}</a></h1>
        <p>{{post.text|safe|truncatechars:200}}</p>
    </div>
{%endfor%}
{%endblock%}

blog_project/mysite/blog/templates/blog/post_form.html
{%extends 'base.html'%}

{%block title_block%}
POST FORM
{%endblock%}

{%block body_block%}
    <h1>NEW POSTt:</h1>
    <form class="post-form" method="POST">
        {%csrf_token%}
        {{form.as_p}}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
    <script>var editor = new MediumEditor('.editable');</script>
{%endblock%}

blog_project/mysite/blog/templates/blog/post_list.html
{%extends 'blog/base.html'%}

{%block title_block%}
POST LIST
{%endblock%}

{%block body_block%}


    <ol>
            {%for post in post_list%}
            <li>
                <div class="post">
                    <h2><a href="{%url 'blog:post_detail' pk=post.pk%}">{{post.title}}</a></h1>
                    <div class="date">
                        <p>Published on: {{post.published_date|date:"d M Y"}}</p>
                    </div>
                    <a href="{%url 'blog:post_detail' pk=post.pk%}">Comments: {{post.approve_comments.count}}</a>
                </div>
            </li>
            <hr>
            
            {%endfor%}

    </ol>



{%endblock%}